# Site settings
title: CloudSync
email: dinesh@codecrux.com
description: > # this means to ignore newlines until "baseurl:"
  CloudSync is the easiest way to connect salesforce to your back-office data system.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cloud-sync.com" # the base hostname & protocol for your site
app_url: "https://app.cloud-sync.com"

twitter_username: datacol
github_username:  datacol

# Build settings
markdown: kramdown
